name: Release package to GitHub Packages
on:
  push:
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Scala with JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: sbt
          check-latest: true

      - name: Publish package
        run: sbt publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}